### PR TITLE
Use Gradle and the JetBrains IntelliJ plugin

### PR DESCRIPTION
**Pull request by bryant1410**
Now the plugin can easily be used and compiled with IntelliJ IDEA (and gradle), or just by running:

```bash
gradle buildPlugin
```

### CODE REVIEW

**Comment by lihaoyi-databricks** [comment]
Looks great! @bryant1410 happy to merge this once you're happy with it

**Comment by bryant1410** [comment]
It should be ready to go!

**Comment by lihaoyi-databricks** [comment]
Building it locally just as a sanity check before merging. `./gradlew` doesn't work, though `gradle` using whatever random version I installed seems to be making progress. Not terribly familiar with gradle, maybe that behavior is what I should expect?

Still churning away, just finished downloading the intellij CE zip, should be done soon

**Comment by lihaoyi-databricks** [comment]
Seems to have succeeded. @bryant1410 `build/distributions/intellij-jsonnet-1.1.zip` is what I should be looking for right?

**Comment by bryant1410** [comment]
> Seems to have succeeded. @bryant1410 `build/distributions/intellij-jsonnet-1.1.zip` is what I should be looking for right?

Yes!

**Comment by lihaoyi-databricks** [comment]
Tested it, works great. I pushed a commit to relax the intellij version requirements, so it can work with the slightly-out-of-date version of IntelliJ we use at work. Thanks for the PR!

**Pull request merged**
